# The main job for the TPCH pipeline
resources:
  jobs:
    tpch_ingestion_job:
      name: tpch_ingestion_job

      schedule:
        # Run every day at 8:37 AM
        quartz_cron_expression: "44 37 8 * * ?"
        timezone_id: Europe/Amsterdam

      email_notifications:
        on_failure:
          - guanjie.shen@databricks.com

      tasks:
        # - task_key: notebook_task
        #   job_cluster_key: job_cluster
        #   notebook_task:
        #     notebook_path: ../src/notebook.ipynb

        - task_key: refresh_pipeline
          pipeline_task:
            pipeline_id: ${resources.pipelines.tpch_ingestion_pipeline.id}

        # - task_key: main_task
        #   depends_on:
        #     - task_key: refresh_pipeline
        #   job_cluster_key: job_cluster
        #   python_wheel_task:
        #     package_name: ingestion_framework
        #     entry_point: main
        #   libraries:
        #     # By default we just include the .whl file generated for the ingestion_framework package.
        #     # See https://docs.databricks.com/dev-tools/bundles/library-dependencies.html
        #     # for more information on how to add other libraries.
        #     - whl: ../dist/*.whl

      # job_clusters:
      #   - job_cluster_key: job_cluster
      #     new_cluster:
      #       spark_version: 13.3.x-scala2.12
      #       node_type_id: Standard_D3_v2
      #       autoscale:
      #           min_workers: 1
      #           max_workers: 4
