# The main job for the NYC Taxi pipeline
resources:
  jobs:
    nyctaxi_ingestion_job:
      name: nyctaxi_ingestion_job

      schedule:
        # Run every day at 8:37 AM MST
        quartz_cron_expression: "44 37 8 * * ?"
        timezone_id: America/Boise

      email_notifications:
        on_failure:
          - guanjie.shen@databricks.com
      tags:
        envionment: ${var.env}
        
      tasks:
        - task_key: refresh_pipeline
          pipeline_task:
            pipeline_id: ${resources.pipelines.nyctaxi_ingestion_pipeline.id}